language: cpp
sudo: required
dist: bionic
compiler:
  - gcc
os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install -y yasm
  - sudo apt-get install -y libsdl2-dev
  - wget "https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz"
  - tar zxvf cmake-3.16.2-Linux-x86_64.tar.gz
  - export PATH=`pwd`/cmake-3.16.2-Linux-x86_64/bin:$PATH

script:
  - mkdir build
  - cd build
  - cmake ../
  - ./json_test

notifications:
  email: false